In [4]:
import pandas as pd

In [5]:
df=pd.read_excel("cars.xls")

In [6]:
df.head()

Price  Mileage   Make    Model      Trim   Type  Cylinder  Liter  \
0  17314.103129     8221  Buick  Century  Sedan 4D  Sedan         6    3.1   
1  17542.036083     9135  Buick  Century  Sedan 4D  Sedan         6    3.1   
2  16218.847862    13196  Buick  Century  Sedan 4D  Sedan         6    3.1   
3  16336.913140    16342  Buick  Century  Sedan 4D  Sedan         6    3.1   
4  16339.170324    19832  Buick  Century  Sedan 4D  Sedan         6    3.1   

   Doors  Cruise  Sound  Leather  
0      4       1      1        1  
1      4       1      1        0  
2      4       1      1        0  
3      4       1      0        0  
4      4       1      0        1

In [7]:
with pd.ExcelWriter("arabadeneme.xlsx") as writer:   #dosyayı excel olarak kaydetme ve sheetlere df1 df2 lerı kaydedebılırız.
    #grafıkler de excele donusturulebılıyor

    df.to_excel(writer, sheet_name="Sheet1")  

    df.to_excel(writer, sheet_name="Sheet2")

# Kmeans, Neigherest Neighbor

In [8]:
from sklearn.cluster import KMeans #KMeans clusteringde kullanılan yöntem
from sklearn.metrics import silhouette_score     #başarı oranını hesaplamak için bunu import ettik

In [9]:
import matplotlib.pyplot as plt

In [10]:
x=df[["Price", "Mileage", "Cylinder"]]

In [11]:
x.head()

Price  Mileage  Cylinder
0  17314.103129     8221         6
1  17542.036083     9135         6
2  16218.847862    13196         6
3  16336.913140    16342         6
4  16339.170324    19832         6

In [13]:
import numpy as np

In [14]:
x = np.array(x)

In [20]:
x

array([[1.73141031e+04, 8.22100000e+03, 6.00000000e+00],
       [1.75420361e+04, 9.13500000e+03, 6.00000000e+00],
       [1.62188479e+04, 1.31960000e+04, 6.00000000e+00],
       ...,
       [1.57311329e+04, 2.04840000e+04, 6.00000000e+00],
       [1.51188932e+04, 2.59790000e+04, 6.00000000e+00],
       [1.35856368e+04, 3.56620000e+04, 6.00000000e+00]])

In [15]:
model=KMeans(n_clusters=5)   #veriyi benzerliklerine gore kumeliyoruz/gruplara ayiriyoruz

In [16]:
model=model.fit(x)

C:\Users\tkaan\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\tkaan\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


In [17]:
tahmin=model.predict(x)

In [18]:
tahmin

array([4, 4, 4, 1, 1, 1, 1, 1, 1, 3, 4, 1, 1, 1, 1, 1, 1, 3, 3, 3, 4, 4,
       4, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 4, 4, 1, 1,
       1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 4, 4, 1, 1, 1, 1,
       1, 1, 3, 3, 4, 4, 4, 4, 2, 2, 2, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 4, 4, 1, 1, 1, 1, 1, 1, 3, 3, 4, 4, 4, 4, 1, 1,
       1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 4, 4, 1, 1, 1, 1, 3, 3,
       3, 3, 4, 4, 4, 1, 1, 1, 1, 1, 1, 3, 4, 1, 1, 1, 1, 1, 3, 3, 3, 3,
       4, 1, 1, 1, 1, 1, 1, 3, 3, 3, 4, 4, 1, 1, 1, 1, 1, 1, 3, 3, 4, 4,
       4, 1, 1, 3, 3, 3, 3, 3, 4, 4, 4, 1, 1, 1, 1, 1, 1, 3, 4, 4, 1, 1,
       1, 1, 1, 1, 1, 3, 4, 1, 1, 1, 1, 1, 3, 3, 3, 3, 4, 4, 1, 1, 1, 1,
       1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 4,

In [19]:
x['cluster']=tahmin

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [21]:
x.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [22]:
x['cluster'].unique()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [23]:
silhouette_score(x, tahmin)    #4 gruba ayirdi birbirine benzerligine bakiyor

0.3550640642212742

In [24]:
#silhouette SCORE İLE KAC GRUBA AYIRMAMIZ GEREKTIGINE BAKIYORUZ

# 4 grubu benzerlıklerıne gore ayırdı

her grubun bır centraıdı var

hangı ılcede ne kadar market acarsan kar edersın

daha fazla acarsan zarar edersın nerde durman gerektıgını soyluyor sana

benzerlıklerıne gore belırledıgı yerınortası yanı konumu oluyor.

enlem boylam verıp en az masrafla buraya getırebılırsınız dıyor

#### Elbow Method - Dirsek Metodu  (siluet scoretu 1-den 10 a kadar farklı gruplara ayır dırsek nerde kırılmaya baslarsa o kadar gruba ayırmanız gerekır)

#### biz 4 dedik ama 4te haklı mıyız onu anlıycaz

In [25]:
clust=x.assign(Cluster=model.labels_)
model.cluster_centers_.astype('int')
model.labels_

AttributeError: 'numpy.ndarray' object has no attribute 'assign'

In [26]:
plt.figure(figsize=(10,6))
plt.scatter(x.Mileage, x.Price, c=tahmin)
plt.xlabel("Mileage")
plt.ylabel("Price")
plt.legend()
plt.colorbar()
plt.show()
#grafıkte 5 farklı renk goruyoruz
#fıyatı dusuk km sı dusuk mavı , fıyatı dusuk kmsı yuksek mor , fıyatı yuksek kmsı yuksek sarı, 
#fıyatı yuksek kmsı dusuk yesıl ama rnkler deıgısyıor grafıkte
#mileage price grubuna ayırdı.
#burada price ve mileagea baktık

AttributeError: 'numpy.ndarray' object has no attribute 'Mileage'

<Figure size 1000x600 with 0 Axes>

In [27]:
plt.figure(figsize=(10,6))
plt.scatter(x.Mileage, x.Price, c=tahmin)
plt.xlabel("Cylinder")  #burada Cylinder ve price a baktik
plt.ylabel("Price")
plt.legend()
plt.colorbar()
plt.show()

AttributeError: 'numpy.ndarray' object has no attribute 'Mileage'

<Figure size 1000x600 with 0 Axes>

In [ ]:
import numpy as np

In [ ]:
# Predicticting the silhouette score for each clusters

allscore=[]
allclusters=[]
sum_of_squared_distances=[]
def clust (clusters):
    for no_of_cluster in np.arange(1,clusters):   # 1 den clustera kadar say phyton sıfırdan sayfamaya baslar burada 1 yazdık 2 den saymaya baslamıs oldu. 1 den 9 a kadar cluster saymıs oldu
        no_of_cluster+=1
        model=KMeans(n_clusters = no_of_cluster)
        model=model.fit(x)   #1-9 kadar yapıyor her seferınde 1 ıcın 2 ıcın vs.
        pred=model.fit_predict(x)
        sum_of_squared_distances.append(model.inertia_)
        score = silhouette_score(x,pred)  #benzerlıgıne bakıyor
        print("Number of cluster {},silhouette{}".format(no_of_cluster,score))
        allscore.append(score)
        allclusters.append(no_of_cluster)
clust(9)

#r2 de regressıonda r2 ne kadar buyukse basarı oranı artıyordu burada dusme nerde durursa ıdeal olan grup sayısı o oluyor. dusme onemlı burada.

In [ ]:
##değişmeyi bıraktıgı yerde bırakıyoruz o da sonrasında hep 0.36, 0.36 dıye devam ettıgı ıcın almıyoruz artık ondan sonrasını

In [ ]:
plt.plot(allclusters,sum_of_squared_distances,marker='x')
plt.xlabel('k')
plt.ylabel('Distortion')
plt.title('The Elbow Method showing optimal K')
plt.show() #4 te kırılma olmuş, kırılma noktası, elbow metodu nerede kırılma varsa cluster yapıyoruz?
#DİRSEK 4 TE KIRILMIS  5 INCI MARKETI ACARSAK ZARARDAYIZ
#4 te dıkeyden yataya dogru donmus o yuzden 4 gruba ayırdık

In [29]:
df

Price  Mileage    Make     Model           Trim   Type  Cylinder  \
0    17314.103129     8221   Buick   Century       Sedan 4D  Sedan         6   
1    17542.036083     9135   Buick   Century       Sedan 4D  Sedan         6   
2    16218.847862    13196   Buick   Century       Sedan 4D  Sedan         6   
3    16336.913140    16342   Buick   Century       Sedan 4D  Sedan         6   
4    16339.170324    19832   Buick   Century       Sedan 4D  Sedan         6   
..            ...      ...     ...       ...            ...    ...       ...   
799  16507.070267    16229  Saturn  L Series  L300 Sedan 4D  Sedan         6   
800  16175.957604    19095  Saturn  L Series  L300 Sedan 4D  Sedan         6   
801  15731.132897    20484  Saturn  L Series  L300 Sedan 4D  Sedan         6   
802  15118.893228    25979  Saturn  L Series  L300 Sedan 4D  Sedan         6   
803  13585.636802    35662  Saturn  L Series  L300 Sedan 4D  Sedan         6   

     Liter  Doors  Cruise  Sound  Leather  
0      3.1      4       1      1        1  
1      3.1      4       1      1        0  
2      3.1      4       1      1        0  
3      3.1      4       1      0        0  
4      3.1      4       1      0        1  
..     ...    ...     ...    ...      ...  
799    3.0      4       1      0        0  
800    3.0      4       1      1        0  
801    3.0      4       1      1        0  
802    3.0      4       1      1        0  
803    3.0      4       1      0        0  

[804 rows x 12 columns]

In [ ]:
x

In [ ]:
d={0:"Ucuz ve az km", 1:"Ucuz ve cok km", 2:"Pahalı ve az km", 3:"Pahalı ve cok km-orta"}   #dictionary  00,01,10,11
x["isim"]=x['cluster'].map(d)

In [ ]:
#bu 3 kolona bakip 3 kolon arasindaki iliskiyi grupladi- cluster 0 1 2 3

In [28]:
x

array([[1.73141031e+04, 8.22100000e+03, 6.00000000e+00],
       [1.75420361e+04, 9.13500000e+03, 6.00000000e+00],
       [1.62188479e+04, 1.31960000e+04, 6.00000000e+00],
       ...,
       [1.57311329e+04, 2.04840000e+04, 6.00000000e+00],
       [1.51188932e+04, 2.59790000e+04, 6.00000000e+00],
       [1.35856368e+04, 3.56620000e+04, 6.00000000e+00]])